# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '11.0'
use_frameworks!

target 'SwiftRecord' do

# Swift
# 图表
pod 'Charts', '= 3.1.1'
# 动画库
pod 'lottie-ios', '= 2.5.0'
# 约束库
pod 'SnapKit', '= 4.0.0'
# 图片库
pod 'Kingfisher', '= 4.8.1'
# 网络库
pod 'Alamofire', '= 4.7.3'
# 键值对库
pod 'AlamofireObjectMapper', '= 5.1.0'
# 下拉刷新库
pod 'ESPullToRefresh', '= 2.7'

end

